version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: {pwd}
      POSTGRES_DB: testagnos
    ports:
      - "5433:5432"

  go:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: {pwd}
      DB_NAME: testagnos
